version: "3.1"
services:
  db:
    image: mysql
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: test-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/
    ports:
      - "8000:80"

  php-fpm:
    build: docker/php-fpm
    container_name: test-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini