<?php

namespace Tests\App\TestCases\User;

use App\Database\Entities\Users\UserGroup;
use Tests\App\TestCases\WithDatabaseTestCase;

/**
 * Class UserGroupTestCase
 * @package Tests\App\TestCases\User
 */
class UserGroupTestCase extends WithDatabaseTestCase
{
    /**
     * @var array
     */
    public static $createGroupData = [
        'name' => 'test group'
    ];

    /**
     * @return \Laravel\Lumen\Application
     */
    public function createApplication(): \Laravel\Lumen\Application
    {
        return parent::createApplication(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array|null $data
     * @return \Illuminate\Http\Request
     */
    public function getRequest(?array $data = null): \Illuminate\Http\Request
    {
        return parent::getRequest($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param $groupData
     */
    public function createGroup($groupData)
    {
        $group = new UserGroup($groupData);
        $this->entityManager->persist($group);
        $this->entityManager->flush();
    }

    public function getArray($response)
    {
        return json_decode($response->getContent(), true);
    }
}