<?php
namespace Tests\App\TestCases\User;

use App\Database\Entities\Users\User;
use Tests\App\TestCases\WithDatabaseTestCase;

/**
 * Class UserTestCase
 * @package Tests\App\TestCases\User
 */
class UserTestCase extends WithDatabaseTestCase
{
    /**
     * @var array
     */
    static protected $createUserData = [
        'email' => 'John.Doe@example.com',
        'first_name' => 'John',
        'last_name' => 'Doe'
    ];

    /**
     * @return \Laravel\Lumen\Application
     */
    public function createApplication(): \Laravel\Lumen\Application
    {
        return parent::createApplication(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array|null $data
     * @return \Illuminate\Http\Request
     */
    public function getRequest(?array $data = null): \Illuminate\Http\Request
    {
        return parent::getRequest($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param $userData
     */
    public function createUser($userData)
    {
        $user = new User($userData);
        $this->entityManager->persist($user);
        $this->entityManager->flush();
    }
}